-- Create a new database WORKWITH DB V1

CREATE DATABASE IF NOT EXISTS workwithdb;

-- SELECT DB
USE workwithdb;

-- CREATE tasks TABLE from workwithdb
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(191) NOT NULL,
    description VARCHAR(300),
    done BOOLEAN NOT NULL DEFAULT 0,
    createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)
